baseurl = "/"
languageCode = 'en-us'
title = 'ann huang'
theme = "astatine"
disqusShortname = "annhuang"

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"

[taxonomies]
    category = "categories"  
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "posts"
    url = "/post/"
    weight = -150

[[menu.main]]
    name = "about"
    url = "/about/"
    weight = -110
    
[[menu.main]]
    name = "tags"
    url = "/tags/"
    weight = -120

[[menu.main]]
    name = "categories"
    url = "/categories/"
    weight = -130

[params]
    description = "the homepage of ann huang"
    authorName = "ann huang"
    [params.imgname]
        name = "img/main.jpg"
        alt = "Profile picture"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"


[sitemap]
  filename = "sitemap.xml"
